model:
  config_path: ./configs/model_configs/llada2_mini
  model_path: TODO/merged4moe/LLaDA2.0-mini # put your model here, which should be converted by `convert_llada2_moe.py` and have the same config as `config_path`
  tokenizer_path: TODO/merged4moe/LLaDA2.0-mini
  attn_implementation: sdpa
  moe_implementation: fused

data:
  train_path: TODO # put your data here
  data_type: conversation
  datasets_type: mapping
  dataloader_type: native
  max_seq_len: 1024
  text_keys: messages
  noise_range_low: 0.3
  noise_range_high: 0.8
  num_workers: 16

train:
  output_dir: ./logs/llada2_mini_dmoe
  data_parallel_mode: fsdp2
  tensor_parallel_size: 1
  ulysses_parallel_size: 1
  expert_parallel_size: 1
  global_batch_size: 4 # should same as gpu count (otherswise, there would be 'Gradient accumulation is not supported with FSDP offload.')
  micro_batch_size: 1
  num_train_epochs: 2
  rmpad: false
  rmpad_with_pos_ids: false
  bsz_warmup_ratio: 0.007
  dyn_bsz_margin: 0
  dyn_bsz_buffer_size: 200
  optimizer: adamw
  beta1: 0.9
  beta2: 0.999
  lr: 2.0e-6
  lr_warmup_ratio: 0.03
  lr_decay_style: cosine
  lr_decay_ratio: 1.0
  weight_decay: 0.01
  max_grad_norm: 1.0
  enable_mixed_precision: true
  enable_gradient_checkpointing: true
  enable_full_shard: true
  enable_fsdp_offload: true
  enable_activation_offload: true
  init_device: meta
  broadcast_model_weights_from_rank0: true
  enable_full_determinism: false
  empty_cache_steps: 500
  ckpt_manager: dcp
  load_checkpoint_path: ""
  save_epochs: 2
  save_hf_weights: true
  block_diffusion_mode: true
  block_size: 32
  same_token_labels: true
  use_wandb: false  # or you can set `wandb_project` and `wandb_name` to trace your training
  log_steps: 1
